services:
  - type: web
    name: menu-formatter-app
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr poppler-utils
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false --server.port=10000
    envVars:
      - key: PORT
        value: 10000